config/routes.rb
Rails.application.routes.draw do

   root to: 'homes#top'


  resources:books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    validates:title,presence:true
    validates:body,presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def news

  end

  def create
    @book=Book.new(book_params)
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      render :index
    end
  end


  def index
    @books=Book.all
     @book=Book.new
  end

  def show
    @book=Book.find(params[:id])
  end

  def edit
    @book=Book.find(params[:id])

  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    book=Book.find(params[:id])
    book.destroy
    flash[:notice] = "successfully"
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%if @book.errors.any?%>
<%=@book.errors.count%>errors
<ul>
    <%@book.errors.full_messages.each do |message|%>
    <li><%=message%></li>
    <%end%>
</ul>
<%end%>
<%=form_with model:@book,url:book_path(@book.id),method: :patch do |f|%>

<div class="field">
<label for="book_title">Title</label><br>
<%=f.text_field:title%><br>
</div>

<div class="field">
<label for="book_body">Body</label><br>
<%=f.text_area:body%><br>
</div>

<%=f.submit"Update Book"%>

<%end%>

<%=link_to "show",book_path(@book.id),class:"link"%>
<%=link_to "back","/books",class:"link"%>

app/views/books/index.html.erb
<%= flash[:notice]%>

<h1 class="books">Books</h1>



<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <%@books.each do |book|%>
    <tbody>
        <tr>
            <td><%=book.title%></td>
            <td><%=book.body%></td>
         <td><span><%=link_to "show",book_path(book.id),class:"link"%></span></td>
         <td><span><%=link_to"Edit",edit_book_path(book.id),class:"link"%></span></td>
         <td><span><%=link_to"Destroy",book_path(book.id),class:"link",method: :delete,"data-confirm"=>"Are you sure?"%></span></td>


        </tr>
    </tbody>
    <% end %>
</table>

<h2>New book</h2>
<%if @book.errors.any?%>
<%=@book.errors.count%>errors
<ul>
    <%@book.errors.full_messages.each do |message|%>
    <li><%=message%></li>
    <%end%>
</ul>
<%end%>


<%=form_with model:@book do |f| %>

<div class="field">
<label for=“book_title”>Title</label><br>
<%=f.text_field:title%><br>
</div>

<div class="field">
<label for=“book_body”>Body</label><br>
<%=f.text_area:body%><br>
</div>

<%=f.submit'Create Book'%>




<%end%>

app/views/books/show.html.erb
<%= flash[:notice]%>
<p class="title">
<strong>Title:</strong>
<%=@book.title%>
</p>

<p class="title">
<strong>Body:</strong>
<%=@book.body%>
</P>

<%=link_to "Edit",edit_book_path(@book.id),class:"link"%>
|

<%=link_to "back","/books",class:"link"%>

app/views/homes/top.html.erb
<h1>
    ようこそ
    <strong>Bookers</strong>
    へ !
</h1>
<body>
<p>
    <strong>Bookers</strong>
では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>

<P>
<%=link_to "start","/books",class:"link"%>
</P>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>